### ISSUE TITLE
RuntimeError: checkpoint url or path is invalid

### ISSUE THREAD

**Issue by tralala87** [camenduru/Video-LLaMA-colab#2]
After running the colab, I get: 

│ /content/Video-LLaMA-hf/app.py:67 in <module>                                │
│                                                                              │
│    64 model_config = cfg.model_cfg                                           │
│    65 model_config.device_8bit = args.gpu_id                                 │
│    66 model_cls = registry.get_model_class(model_config.arch)                │
│ ❱  67 model = model_cls.from_config(model_config).to('cuda:{}'.format(args.g │
│    68                                                                        │
│    69 vis_processor_cfg = cfg.datasets_cfg.webvid.vis_processor.train        │
│    70 vis_processor = registry.get_processor_class(vis_processor_cfg.name).f │
│                                                                              │
│ /content/Video-LLaMA-hf/video_llama/models/video_llama.py:394 in from_config │
│                                                                              │
│   391 │   │   fusion_head_layers = cfg.get("fusion_head_layers", 2)          │
│   392 │   │   num_video_query_token =  cfg.get("num_video_query_token", 32)  │
│   393 │   │                                                                  │
│ ❱ 394 │   │   model = cls(                                                   │
│   395 │   │   │   vit_model=vit_model,                                       │
│   396 │   │   │   q_former_model=q_former_model,                             │
│   397 │   │   │   img_size=img_size,                                         │
│                                                                              │
│ /content/Video-LLaMA-hf/video_llama/models/video_llama.py:102 in __init__    │
│                                                                              │
│    99 │   │   for layer in self.Qformer.bert.encoder.layer:                  │
│   100 │   │   │   layer.output = None                                        │
│   101 │   │   │   layer.intermediate = None                                  │
│ ❱ 102 │   │   self.load_from_pretrained(url_or_filename=q_former_model)      │
│   103 │   │                                                                  │
│   104 │   │   if freeze_qformer:                                             │
│   105 │   │   │   for name, param in self.Qformer.named_parameters():        │
│                                                                              │
│ /content/Video-LLaMA-hf/video_llama/models/blip2.py:82 in                    │
│ load_from_pretrained                                                         │
│                                                                              │
│    79 │   │   elif os.path.isfile(url_or_filename):                          │
│    80 │   │   │   checkpoint = torch.load(url_or_filename, map_location="cpu │
│    81 │   │   else:                                                          │
│ ❱  82 │   │   │   raise RuntimeError("checkpoint url or path is invalid")    │
│    83 │   │                                                                  │
│    84 │   │   state_dict = checkpoint["model"]

**Comment by camenduru** [comment]
please try again
